import {
  Autoformat,
  Autosave,
  BlockQuote,
  Bold,
  CKFinder,
  CKFinderUploadAdapter,
  ClassicEditor,
  Clipboard,
  Code,
  CodeBlock,
  Enter,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Highlight,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Italic,
  Link,
  List,
  ListProperties,
  MediaEmbed,
  Paragraph,
  RemoveFormat,
  SelectAll,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableProperties,
  TableToolbar,
  Typing,
  Underline,
  Undo,
} from 'ckeditor5';

import { InsertFile } from './insert-file.plugin';

export interface FileAttachment {
  file: File;
  fileHash: string;
  fileExtension: string;
}

declare module 'ckeditor5' {
  interface Editor {
    fileAttachments?: FileAttachment[];
  }
}

export { ClassicEditor };

export const PLUGINS = [
  Autoformat,
  Autosave,
  BlockQuote,
  Bold,
  CKFinder,
  InsertFile,
  CKFinderUploadAdapter,
  Clipboard,
  Code,
  CodeBlock,
  Enter,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Highlight,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Italic,
  Link,
  List,
  ListProperties,
  MediaEmbed,
  Paragraph,
  RemoveFormat,
  SelectAll,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableProperties,
  TableToolbar,
  Typing,
  Underline,
  Undo,
];
