include:
  - sci-log-db/compose.yaml

services:
  frontend:
    build:
      context: ./scilog/.
      target: builder
    environment:
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
    volumes:
      - ./scilog:/frontend
      - ./config/fe/config.dev.json:/frontend/src/assets/config.json
      - /frontend/node_modules
      - /frontend/dist
    command: ["npm", "run", "dev"]
    profiles:
      - fe
    ports:
      - 4200:4200

  python:
    build:
      context: ./importTools
    volumes:
      - ./importTools:/usr/src/app
      - ./sdk/python/scilog:/usr/local/lib/python3.10/site-packages/scilog
    # infinite loop to keep the container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    profiles:
      - py
