services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
      - ./config/mongo/rs-init.sh:/rs-init.sh:ro
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ./rs-init.sh
      interval: 5s
    profiles: 
      - be
      - bf
      - bfp
      - bp

  backend:
    build: 
      context: ./sci-log-db/.
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./sci-log-db:/home/node/app
      - ./config/be/oidc.json:/home/node/app/oidc.json
      - ./config/be/datasource.json:/home/node/app/datasource.json
      # - ./config/be/roles.js:/home/node/app/dist/authentication-strategies/roles.js
      - ./sci-log-db/functionalAccounts-example.json:/home/node/app/functionalAccounts.json
      - /home/node/app/node_modules
      - /home/node/app/dist
    environment:
      JWT_SECRET: jwt_secret
      CHROME_BIN: /usr/bin/chromium
      CHROME_PATH: /usr/lib/chromium/
    command: /bin/sh -c "while true; do sleep 600; done"
    profiles: 
      - be
      - bf
      - bfp
      - bp

  frontend:
    build: 
      context: ./scilog/.
      target: builder
    environment:
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
    volumes:
      - ./scilog:/frontend
      - ./config/fe/config.json:/frontend/src/assets/config.json
      - /frontend/node_modules
      - /frontend/dist
    command: /bin/sh -c "apk add --no-cache chromium && while true; do sleep 600; done"
    profiles: 
      - fe
      - bf
      - fp
      - bfp

  python: 
    build:
      context: ./importTools
    volumes:
        - ./importTools:/usr/src/app
        - ./sdk/python/scilog:/usr/local/lib/python3.10/site-packages/scilog
    # infinite loop to keep the container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    profiles: 
      - py
      - bp
      - fp
      - bfp


volumes:
  mongodb_data:
    driver: local
