services:
  mongo:
    image: bitnamilegacy/mongodb:4.4
    volumes:
      - "mongo_data:/bitnami"
  scilog:
    build:
        context: .
    command: npm run test
    depends_on:
        - mongo

volumes:
  mongo_data:
