# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.view_include_filter_items import ViewIncludeFilterItems  # noqa: E501
from swagger_client.rest import ApiException


class TestViewIncludeFilterItems(unittest.TestCase):
    """ViewIncludeFilterItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testViewIncludeFilterItems(self):
        """Test ViewIncludeFilterItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.view_include_filter_items.ViewIncludeFilterItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
