# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.new_viewtitle_new_viewexclude_iddeprecated_owner_groupaccess_groups import NewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups  # noqa: E501
from swagger_client.rest import ApiException


class TestNewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups(unittest.TestCase):
    """NewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups(self):
        """Test NewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.new_viewtitle_new_viewexclude_iddeprecated_owner_groupaccess_groups.NewViewtitleNewViewexcludeIddeprecatedOwnerGroupaccessGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
