# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.new_logbooktitle_new_logbookexclude_iddeprecated_owner_groupaccess_groups import NewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups  # noqa: E501
from swagger_client.rest import ApiException


class TestNewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups(unittest.TestCase):
    """NewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups(self):
        """Test NewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.new_logbooktitle_new_logbookexclude_iddeprecated_owner_groupaccess_groups.NewLogbooktitleNewLogbookexcludeIddeprecatedOwnerGroupaccessGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
