# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.image_controller_api import ImageControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImageControllerApi(unittest.TestCase):
    """ImageControllerApi unit test stubs"""

    def setUp(self):
        self.api = ImageControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_image_controller_download_file(self):
        """Test case for image_controller_download_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
