# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.file_controller_api import FileControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileControllerApi(unittest.TestCase):
    """FileControllerApi unit test stubs"""

    def setUp(self):
        self.api = FileControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_file_controller_count(self):
        """Test case for file_controller_count

        """
        pass

    def test_file_controller_create(self):
        """Test case for file_controller_create

        """
        pass

    def test_file_controller_delete_by_id(self):
        """Test case for file_controller_delete_by_id

        """
        pass

    def test_file_controller_download_file(self):
        """Test case for file_controller_download_file

        """
        pass

    def test_file_controller_file_upload(self):
        """Test case for file_controller_file_upload

        """
        pass

    def test_file_controller_find(self):
        """Test case for file_controller_find

        """
        pass

    def test_file_controller_find_by_id(self):
        """Test case for file_controller_find_by_id

        """
        pass

    def test_file_controller_find_index_in_buffer(self):
        """Test case for file_controller_find_index_in_buffer

        """
        pass

    def test_file_controller_find_with_search(self):
        """Test case for file_controller_find_with_search

        """
        pass

    def test_file_controller_restore_deleted_id(self):
        """Test case for file_controller_restore_deleted_id

        """
        pass

    def test_file_controller_update_all(self):
        """Test case for file_controller_update_all

        """
        pass

    def test_file_controller_update_by_id(self):
        """Test case for file_controller_update_by_id

        """
        pass

    def test_file_controller_update_by_id_with_file(self):
        """Test case for file_controller_update_by_id_with_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
