# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.job_controller_api import JobControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobControllerApi(unittest.TestCase):
    """JobControllerApi unit test stubs"""

    def setUp(self):
        self.api = JobControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_job_controller_count(self):
        """Test case for job_controller_count

        """
        pass

    def test_job_controller_create(self):
        """Test case for job_controller_create

        """
        pass

    def test_job_controller_delete_by_id(self):
        """Test case for job_controller_delete_by_id

        """
        pass

    def test_job_controller_find(self):
        """Test case for job_controller_find

        """
        pass

    def test_job_controller_find_by_id(self):
        """Test case for job_controller_find_by_id

        """
        pass

    def test_job_controller_update_all(self):
        """Test case for job_controller_update_all

        """
        pass

    def test_job_controller_update_by_id(self):
        """Test case for job_controller_update_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
