# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_preference_scope_filter import UserPreferenceScopeFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestUserPreferenceScopeFilter(unittest.TestCase):
    """UserPreferenceScopeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPreferenceScopeFilter(self):
        """Test UserPreferenceScopeFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_preference_scope_filter.UserPreferenceScopeFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
