# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.oidc_controller_api import OIDCControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOIDCControllerApi(unittest.TestCase):
    """OIDCControllerApi unit test stubs"""

    def setUp(self):
        self.api = OIDCControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_o_idc_controller_login_to_third_party(self):
        """Test case for o_idc_controller_login_to_third_party

        """
        pass

    def test_o_idc_controller_third_party_call_back(self):
        """Test case for o_idc_controller_third_party_call_back

        """
        pass


if __name__ == '__main__':
    unittest.main()
