# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.basesnippet_include_filter_items1 import BasesnippetIncludeFilterItems1  # noqa: E501
from swagger_client.rest import ApiException


class TestBasesnippetIncludeFilterItems1(unittest.TestCase):
    """BasesnippetIncludeFilterItems1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasesnippetIncludeFilterItems1(self):
        """Test BasesnippetIncludeFilterItems1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.basesnippet_include_filter_items1.BasesnippetIncludeFilterItems1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
