# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.task_filter1 import TaskFilter1  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskFilter1(unittest.TestCase):
    """TaskFilter1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskFilter1(self):
        """Test TaskFilter1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_filter1.TaskFilter1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
