# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_basesnippet_scope_filter1_fields import OneOfBasesnippetScopeFilter1Fields  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfBasesnippetScopeFilter1Fields(unittest.TestCase):
    """OneOfBasesnippetScopeFilter1Fields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfBasesnippetScopeFilter1Fields(self):
        """Test OneOfBasesnippetScopeFilter1Fields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_basesnippet_scope_filter1_fields.OneOfBasesnippetScopeFilter1Fields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
