# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_filesnippet_scope_filter_order import OneOfFilesnippetScopeFilterOrder  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfFilesnippetScopeFilterOrder(unittest.TestCase):
    """OneOfFilesnippetScopeFilterOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilesnippetScopeFilterOrder(self):
        """Test OneOfFilesnippetScopeFilterOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_filesnippet_scope_filter_order.OneOfFilesnippetScopeFilterOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
