# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_view_scope_filter1_fields import OneOfViewScopeFilter1Fields  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfViewScopeFilter1Fields(unittest.TestCase):
    """OneOfViewScopeFilter1Fields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfViewScopeFilter1Fields(self):
        """Test OneOfViewScopeFilter1Fields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_view_scope_filter1_fields.OneOfViewScopeFilter1Fields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
