# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_task_filter2_order import OneOfTaskFilter2Order  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfTaskFilter2Order(unittest.TestCase):
    """OneOfTaskFilter2Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfTaskFilter2Order(self):
        """Test OneOfTaskFilter2Order"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_task_filter2_order.OneOfTaskFilter2Order()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
