# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.filesnippet_files_body import FilesnippetFilesBody  # noqa: E501
from swagger_client.rest import ApiException


class TestFilesnippetFilesBody(unittest.TestCase):
    """FilesnippetFilesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesnippetFilesBody(self):
        """Test FilesnippetFilesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.filesnippet_files_body.FilesnippetFilesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
