# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_basesnippet_scope_filter1_order import OneOfBasesnippetScopeFilter1Order  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfBasesnippetScopeFilter1Order(unittest.TestCase):
    """OneOfBasesnippetScopeFilter1Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfBasesnippetScopeFilter1Order(self):
        """Test OneOfBasesnippetScopeFilter1Order"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_basesnippet_scope_filter1_order.OneOfBasesnippetScopeFilter1Order()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
