# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_job_filter1_order import OneOfJobFilter1Order  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfJobFilter1Order(unittest.TestCase):
    """OneOfJobFilter1Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfJobFilter1Order(self):
        """Test OneOfJobFilter1Order"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_job_filter1_order.OneOfJobFilter1Order()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
