# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_location_filter_order import OneOfLocationFilterOrder  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfLocationFilterOrder(unittest.TestCase):
    """OneOfLocationFilterOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfLocationFilterOrder(self):
        """Test OneOfLocationFilterOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_location_filter_order.OneOfLocationFilterOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
