# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_preference_filter1 import UserPreferenceFilter1  # noqa: E501
from swagger_client.rest import ApiException


class TestUserPreferenceFilter1(unittest.TestCase):
    """UserPreferenceFilter1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPreferenceFilter1(self):
        """Test UserPreferenceFilter1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_preference_filter1.UserPreferenceFilter1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
