# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paragraph_groups_compatibleinclude_relationstruedeprecated_owner_groupaccess_groups import ParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups  # noqa: E501
from swagger_client.rest import ApiException


class TestParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups(unittest.TestCase):
    """ParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups(self):
        """Test ParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paragraph_groups_compatibleinclude_relationstruedeprecated_owner_groupaccess_groups.ParagraphGroupsCompatibleincludeRelationstruedeprecatedOwnerGroupaccessGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
