# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_credentials_with_relations import UserCredentialsWithRelations  # noqa: E501
from swagger_client.rest import ApiException


class TestUserCredentialsWithRelations(unittest.TestCase):
    """UserCredentialsWithRelations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCredentialsWithRelations(self):
        """Test UserCredentialsWithRelations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_credentials_with_relations.UserCredentialsWithRelations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
