# coding: utf-8

"""
    sci-log-db

    SciLogDB  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.logbook_filter1 import LogbookFilter1  # noqa: E501
from swagger_client.rest import ApiException


class TestLogbookFilter1(unittest.TestCase):
    """LogbookFilter1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogbookFilter1(self):
        """Test LogbookFilter1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.logbook_filter1.LogbookFilter1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
