services:
  scilog:
    build: 
      context: .
      target: builder
    environment:
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
    command: /bin/sh -c "apk add --no-cache chromium && npm run test:CI"
