version: "3.9"
services:
  reverse-proxy:
    image: traefik:3.2
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
#      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - prox

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
      - ./mongo/rs-init.sh:/rs-init.sh:ro
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    healthcheck:
      test: ./rs-init.sh
      interval: 5s
    profiles:
      - be
      - prox

  mongodb_seed:
    image: mongo:4.2
    volumes:
      - ./seed_db/seed:/seed
      - ./seed_db/mongo_import.sh:/mnt/mongo_import.sh
    command:
      - "sh"
      - "-c"
      - "chmod u+x /mnt/mongo_import.sh && /mnt/mongo_import.sh"
    user: "0:0"
    depends_on:
      - mongodb
    environment:
      - DATABASE=scilog
    restart: on-failure
    profiles:
      - be
      - prox

  backend:
    image: ghcr.io/paulscherrerinstitute/scilog/be
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      # uncomment and edit the ./be/oidc.json to enable oidc
      # for keycloak get your config values from: YOURKC_URL/realms/YOUR_REALM/.well-known/openid-configuration or YOURKC_URL/auth/realms/YOUR_REALM/.well-known/openid-configuration for older keycloak versions
      # - ./be/oidc.json:/home/node/app/oidc.json
      - ./be/datasource.json:/home/node/app/datasource.json
      - ./be/functionalAccounts.json:/home/node/app/functionalAccounts.json
    environment:
      JWT_SECRET: jwt_secret
      CHROME_BIN: /usr/bin/chromium
      CHROME_PATH: /usr/lib/chromium/
    profiles:
      - be
      - prox
    #ports:
    #  - 3000:3000
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)||PathPrefix(`/explorer`)||PathPrefix(`/users`)||PathPrefix(`/locations`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.forceSlash=false"

  frontend:
    image: ghcr.io/paulscherrerinstitute/scilog/fe
    volumes:
    #   uncomment to enable the oidc form
    #  - ./fe/config.json:/usr/share/nginx/html/assets/config.json
    #   uncomment to enable use on non-localhost accesst to demo login
       - ./fe/simple_config.json:/usr/share/nginx/html/assets/config.json
    profiles:
      - fe
      - prox
    #ports:
    #  - 80:80
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

volumes:
  mongodb_data:
    driver: local
