# coding: utf-8

"""
    pan-ontologies

    A pan-ontologies API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: carlo.minotti@psi.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ping_controller_api import PingControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPingControllerApi(unittest.TestCase):
    """PingControllerApi unit test stubs"""

    def setUp(self):
        self.api = PingControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ping_controller_ping(self):
        """Test case for ping_controller_ping

        """
        pass


if __name__ == '__main__':
    unittest.main()
