# coding: utf-8

"""
    pan-ontologies

    A pan-ontologies API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: carlo.minotti@psi.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.technique_controller_api import TechniqueControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTechniqueControllerApi(unittest.TestCase):
    """TechniqueControllerApi unit test stubs"""

    def setUp(self):
        self.api = TechniqueControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_technique_controller_count(self):
        """Test case for technique_controller_count

        """
        pass

    def test_technique_controller_find(self):
        """Test case for technique_controller_find

        """
        pass

    def test_technique_controller_find_by_id(self):
        """Test case for technique_controller_find_by_id

        """
        pass

    def test_technique_controller_find_pan_ontology(self):
        """Test case for technique_controller_find_pan_ontology

        """
        pass


if __name__ == '__main__':
    unittest.main()
