# coding: utf-8

"""
    pan-ontologies

    A pan-ontologies API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: carlo.minotti@psi.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_technique_filter_order import OneOfTechniqueFilterOrder  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfTechniqueFilterOrder(unittest.TestCase):
    """OneOfTechniqueFilterOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfTechniqueFilterOrder(self):
        """Test OneOfTechniqueFilterOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_technique_filter_order.OneOfTechniqueFilterOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
