# coding: utf-8

"""
    pan-ontologies

    A pan-ontologies API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: carlo.minotti@psi.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_technique_filter1_fields import OneOfTechniqueFilter1Fields  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfTechniqueFilter1Fields(unittest.TestCase):
    """OneOfTechniqueFilter1Fields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfTechniqueFilter1Fields(self):
        """Test OneOfTechniqueFilter1Fields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_technique_filter1_fields.OneOfTechniqueFilter1Fields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
