name: Import tools formatting

on:
  pull_request:
    branches: [main]
    paths: 
      - importTools/**
      - .github/workflows/black.importTools-python.yaml
  push:
    branches: [main]
    paths: 
      - importTools/**
      - .github/workflows/black.importTools-python.yaml
  release:
    types: [published]
    paths: 
      - importTools/**
      - .github/workflows/black.importTools-python.yaml

jobs:
  test:
    name: Test and build image on PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: importTools

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -e .

      - name: Lint with black
        run: |
          black --check --diff --no-color --line-length=100 .
