name: Demo formatting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  black:
    uses: ./.github/workflows/reusable.python-black.yaml
    with: 
      working-directory: demo
