name: Build and deploy docu

on:
  push:
    branches: [main]
    paths: 
      - docs/**
      - .github/workflows/deploy-docu.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Build
        run: |
          cd docs
          npm install
          npx honkit build . docs

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc # v3.2.0
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: true
          build_dir: docs/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
