name: Semantic Commit Validator

on:
  merge_group:
    types:
      - checks_requested

jobs:
  commitlint:
    name: Lint Squashed Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: Validate Last Commit Message
        run: npx commitlint --last --verbose
