name: Test && Build && Push

on:
  pull_request:
    branches: [main]
    paths:
      - web/**
      - .github/workflows/test-build-push.fe.yaml
  push:
    branches: [main]
    paths:
      - web/**
      - .github/workflows/test-build-push.fe.yaml
  release:
    types: [published]

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/fe
  CONTEXT: web

jobs:
  test:
    name: Lint, test and build image on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags
        id: tags
        run: |
          prefix=$CONTAINER_REGISTRY/$IMAGE_NAME
          tags=$prefix:"${{ github.sha }}"
          if [[ "${{ github.event_name }}" == "release" ]]; then
            tags=$prefix:"${{ github.event.release.tag_name }}",$prefix:stable
          fi
          echo "tags=$tags,$prefix:latest" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: ${{ env.CONTEXT }}/.
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
